[package]
name = "controller"
version = "0.1.0"
authors = ["Minterest <https://github.com/minterest-defi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }

orml-traits = { path = "../../orml/traits", default-features = false }

minterest-primitives = { path = "../../primitives", default-features = false }
m-tokens = { path = "../m-tokens", default-features = false }
liquidity-pools = { path = "../liquidity-pools", default-features = false }


[dev-dependencies]
#liquidity-pools = { path = "../liquidity-pools" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "minterest-primitives/std",
    "m-tokens/std",
]