[package]
name = "minterest-primitives"
version = "0.5.0"
authors = ['Minterest <https://github.com/minterest-defi>']
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
serde = { version = "1.0.101", optional = true }
sp-core = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-runtime/std",
    "serde",
    "sp-core/std",
    'sp-std/std',
]
