[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',

    'pallets/liquidity-pools',
    'pallets/m-tokens',
    'pallets/minterest-protocol',
    'pallets/controller',
    'pallets/accounts',
    'pallets/oracle',

    'primitives',

    "orml/auction",
    "orml/authority",
    "orml/benchmarking",
    "orml/currencies",
    "orml/gradually-update",
    "orml/oracle",
    "orml/tokens",
    "orml/traits",
    "orml/utilities",
    "orml/vesting",
]
