[package]
name = "minterest-chain"
version = "0.6.2"
authors = ["Minterest <https://github.com/minterest-defi>"]
edition = "2018"

[profile.release]
panic = 'unwind'

[[bin]]
name = "minterest"
path = "src/main.rs"

[dependencies]
cargo-audit = "0.14.0"
minterest-cli = { path = "cli" }
minterest-service = { path = "service" }
orml-oracle = "0.4.0"

[features]
runtime-benchmarks = [
    "minterest-cli/runtime-benchmarks",
]

[workspace]
members = [
    'cli',
    'rpc',
    'primitives',
    'service',
    'runtime',
    'pallets/liquidity-pools',
    'pallets/minterest-model',
    'pallets/minterest-protocol',
    'pallets/controller',
    'pallets/prices',
    'pallets/risk-manager',
    'pallets/liquidation-pools',
    'pallets/mnt-token',
    'pallets/dex',
]

