[package]
name = "minterest-chain"
version = "0.6.0"
authors = ["Minterest <https://github.com/minterest-defi>"]
edition = "2018"

[profile.release]
panic = 'unwind'

[[bin]]
name = "minterest"
path = "src/main.rs"

[dependencies]
minterest-cli = { path = "cli" }
minterest-service = { path = "service" }

[features]
runtime-benchmarks = [
    "minterest-cli/runtime-benchmarks",
]

[workspace]
members = [
    'cli',
    'rpc',
    'primitives',
    'service',
    'runtime',
    'modules/liquidity-pools',
    'modules/m-tokens',
    'modules/minterest-model',
    'modules/minterest-protocol',
    'modules/controller',
    'modules/accounts',
    'modules/oracle',
    'modules/risk-manager',
    'modules/liquidation-pools',

    "orml/auction",
    "orml/authority",
    "orml/benchmarking",
    "orml/currencies",
    "orml/gradually-update",
    "orml/oracle",
    "orml/tokens",
    "orml/traits",
    "orml/utilities",
    "orml/vesting",
]

