[package]
name = "minterest-service"
version = "0.5.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
hex-literal = "0.3.1"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
codec = { package = "parity-scale-codec", version = "2.0.0" }
sp-api = { version = "3.0.0" }
sp-consensus = { version = "0.9.0" }
sp-consensus-aura = { version = "0.9.0" }
sp-core = { version = "3.0.0" }
pallet-membership = { version = "3.0.0" }
pallet-collective = { version = "3.0.0" }
sp-finality-grandpa = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }
sp-inherents = { version = "3.0.0" }
sc-finality-grandpa = { version = "0.9.0" }
sc-chain-spec = { version = "3.0.0" }
sc-client-api = { version = "3.0.0" }
sc-telemetry = { version = "3.0.0" }
sc-service = { version = "0.9.0" }
sc-executor = { version = "0.9.0" }
sc-consensus = { version = "0.9.0" }
sc-consensus-aura = { version = "0.9.0" }
sc-consensus-manual-seal = { version = "0.9.0" }
sc-consensus-slots = { version = "0.9.0" }
sc-transaction-pool = { version = "3.0.0" }
sc-basic-authorship = { version = "0.9.0" }
sc-network = { version = "0.9.0" }
sc-keystore = { version = "3.0.0" }
sp-keystore = { version = "0.9.0" }
frame-benchmarking = { version = "3.0.0" }
sp-trie = { version = "3.0.0" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.9.0"}

sp-block-builder = { version = "3.0.0" }
frame-system-rpc-runtime-api = { version = "3.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0" }
sp-offchain = { version = "3.0.0" }
sp-session = { version = "3.0.0" }
sp-storage = { version = "3.0.0" }
sp-transaction-pool = { version = "3.0.0" }
sp-blockchain = { version = "3.0.0" }
sp-std = { version = "3.0.0" }

# local dependencies
minterest-rpc = { path = "../rpc" }
controller = { path = "../pallets/controller" }
liquidity-pools = { path = "../pallets/liquidity-pools" }
liquidation-pools = { path = "../pallets/liquidation-pools" }
minterest-model = { path = "../pallets/minterest-model" }
risk-manager = { path = "../pallets/risk-manager" }
module-vesting = { path = "../pallets/vesting" }
minterest-primitives = { path = "../primitives" }

node-minterest-runtime = { path = '../runtime' }

[features]
default = ["std"]
std = []
runtime-benchmarks = [
    'node-minterest-runtime/runtime-benchmarks',
]
