[package]
name = "minterest-cli"
version = "0.5.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
structopt = "0.3.8"
sp-core = { version = "3.0.0", optional = true }
sc-cli = { version = "0.9.0", optional = true }
sc-service = { version = "0.9.0", optional = true }
frame-benchmarking-cli = { version = "3.0.0", optional = true }

service = { package = "minterest-service", path = "../service", default-features = false, optional = true }
node-minterest-runtime = { path = '../runtime' }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", default-features = false }

[features]
default = ["wasmtime", "cli"]
wasmtime = [ "sc-cli/wasmtime" ]
cli = [
    "service",
    "sp-core",
    "sc-cli",
    "sc-service",
    "frame-benchmarking-cli",
]
runtime-benchmarks = [ "service/runtime-benchmarks" ]
