[package]
name = "prices-rpc"
version = "0.1.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"

sp-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

prices-rpc-runtime-api = { path = "runtime-api" }
minterest-primitives = { path = "../../../primitives" }
