[package]
name = "prices-rpc"
version = "0.1.0"
authors = ["Minterest developers"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"

sc-rpc = "3.0"
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }

prices-rpc-runtime-api = { path = "runtime-api" }
minterest-primitives = { path = "../../../primitives" }
