[package]
name = "integration-tests"
description = 'Integration tests'
version = "0.5.0"
authors = ['Minterest <https://github.com/minterest-defi>']
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-std = { version = "3.0.0", default-features = false }

orml-utilities = { path = "../../orml/utilities", default-features = false }

minterest-primitives = { path = "../../primitives", default-features = false }
m-tokens = { path = "../m-tokens", default-features = false }
liquidity-pools = { path = "../liquidity-pools", default-features = false }
minterest-protocol = { path = "../minterest-protocol", default-features = false }

[dev-dependencies]
sp-core = { version = "3.0.0" }
sp-io = { version = "3.0.0" }
sp-runtime = { version = "3.0.0" }

orml-tokens = { path = "../../orml/tokens" }
orml-currencies = { path = "../../orml/currencies" }
orml-traits = { path = "../../orml/traits" }

liquidity-pools = { path = "../liquidity-pools" }
controller = { path = "../controller" }
oracle = { path = "../oracle" }
pallet-traits = { path = "../traits" }
accounts = { path = "../accounts" }
minterest-model = { path = "../minterest-model" }
minterest-protocol = { path = "../minterest-protocol" }

[features]
default = ['std']
std = [
    'codec/std',
    "sp-runtime/std",
    'frame-support/std',
    'frame-system/std',
    "sp-std/std",

    "orml-utilities/std",

    "minterest-primitives/std",
    "m-tokens/std",
    "liquidity-pools/std",
    "minterest-protocol/std",
]

