# Example `~/.cargo/audit.toml` file
# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.

[advisories]
ignore = [
    "RUSTSEC-2021-0013",
    "RUSTSEC-2021-0067",
    "RUSTSEC-2021-0070",
    "RUSTSEC-2021-0060",
    "RUSTSEC-2021-0073",
    "RUSTSEC-2021-0059",
    "RUSTSEC-2021-0057",
    "RUSTSEC-2021-0064",
    "RUSTSEC-2021-0036",
    "RUSTSEC-2021-0016"
]
