[package]
name = "controller-rpc-runtime-api"
version = "0.1.0"
authors = ["Minterest <https://github.com/minterest-defi>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0-alpha.6", default-features = false }

minterest-primitives = { path = "../../../../primitives", default-features = false }


[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-api/std",
    "sp-std/std",
    "sp-arithmetic/std",
    "minterest-primitives/std",
]
