[package]
name = "minterest-protocol"
description = 'Pallet for minteres protocol implementation'
version = "0.1.0"
authors = ['Minterest <https://github.com/minterest-defi>']
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
sp-std = { version = "2.0.0", default-features = false }

orml-traits = { path = "../../orml/traits", default-features = false }
orml-utilities = { path = "../../orml/utilities", default-features = false }

minterest-primitives = { path = "../../primitives", default-features = false }
m-tokens = { path = "../m-tokens", default-features = false }
pallet-traits = { path = "../traits", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false }
orml-tokens = { path = "../../orml/tokens"}
orml-currencies = { path = "../../orml/currencies"}

[features]
default = ['std']
std = [
    'codec/std',
    "sp-std/std",
    "sp-runtime/std",
    'frame-support/std',
    'frame-system/std',
    "orml-traits/std",
    "minterest-primitives/std",
    "m-tokens/std",
    "pallet-traits/std",
]
