[package]
name = "minterest-protocol"
description = 'Pallet for minteres protocol implementation'
version = "0.1.0"
authors = ['Minterest <https://github.com/minterest-defi>']
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
sp-std = { version = "2.0.0", default-features = false }

orml-utilities = { path = "../../orml/utilities", default-features = false }
orml-traits = { path = "../../orml/traits", default-features = false }

minterest-primitives = { path = "../../primitives", default-features = false }
liquidity-pools = { path = "../liquidity-pools", default-features = false }
pallet-traits = { path = "../traits", default-features = false }
controller = { path = "../controller", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0" }
orml-tokens = { path = "../../orml/tokens" }
orml-currencies = { path = "../../orml/currencies" }
sp-io = { version = "2.0.0" }
liquidity-pools = { path = "../liquidity-pools" }
oracle = { path = "../oracle" }
controller = { path = "../controller" }
accounts = { path = "../accounts" }

[features]
default = ['std']
std = [
    'codec/std',
    "sp-std/std",
    "sp-runtime/std",
    'frame-support/std',
    'frame-system/std',
    "minterest-primitives/std",
]
