name: Security audit
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: ctions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
